version: '3.7'

services: 
  # tazk-backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile

  #   ports:
  #     - "8747:8747"
    
  #   environment:
  #     - NODE_ENV=development
  #     - PORT=8747
  #     - MONGO_URI=mongodb://admin:password@tazk-mongo:27017/
    
  #   depends_on:
  #     - tazk-mongo
    
  #   networks:
  #     - tazk-network
    
  #   volumes:
  #     - .:/app
  
  tazk-mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - tazk-network
    volumes:
      - tazk-mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  database:
    image: mongo-express
    ports:
      - "8081:8081"
    networks:
      - tazk-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=tazk-mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    depends_on:
      - tazk-mongo
    
  

volumes:
  tazk-mongo-data:
    
networks:
  tazk-network:
    driver: bridge