name: "CICD"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      
      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm test
  
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run 
  
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Build Backend Docker image
        run: docker build -t tazk-backend:0.0.0 ./tazk-backend

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Tag Docker image
        run: docker tag tazk-backend:0.0.0 ${{ secrets.DOCKERHUB_USERNAME}}/tazk:0.0.0

      - name: Push Backend Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/tazk:0.0.0